fix: human event timestamps #170
Streali/App pull request #173
Opened 2023-01-06 14:09 UTC by nicolas-besnard

# What does this PR do?

Refresh the human timestamp on the events list

> Screenshot of the feature

I couldn't provide a screenshot, because the item is updating every minute

---

## PR Checklist

### Global

- [x] This PR does not introduce any breaking change
- [ ] This PR introduces breaking change(s) and has been labeled as such
- [ ] I have found someone to review this PR and pinged him

### Clean Code

- [x] I made sure the code is type safe (no any)
- [ ] I have included a feature flag on my feature, if applicable

2023-01-06 21:57 UTC, RomainLanz requested changes

2023-01-06 21:57 UTC, RomainLanz commented on src/pages/events.tsx
> +
```suggestion
```

2023-01-06 21:57 UTC, RomainLanz commented on src/pages/events.tsx
> +function useDynamicRenderKey(intervalInMs = 1_000 * 60) {
This should be externalize in `~/hooks/core`

2023-01-06 21:57 UTC, RomainLanz commented
Great work!

We should also handle this in the dashboard `~/pages/dashboard.tsx`.

2023-01-06 22:19 UTC, nicolas-besnard commented on src/pages/events.tsx
> +function useDynamicRenderKey(intervalInMs = 1_000 * 60) {
fixed in 8d077a1

2023-01-06 23:51 UTC, RomainLanz approved these changes

2023-01-08 22:28 UTC, WilliamTraoreee commented
@nicolas-besnard I can't merge your PR because he has some conflicts on it. Can you fix that ? :D

2023-01-10 22:08 UTC, merged

2023-01-10 22:08 UTC, RomainLanz commented
Thanks!